### ISSUE TITLE
micro FA and INVF (ex-vivo)

### ISSUE THREAD

**Issue by dicemt** [ekaden/smt#2]
Hi,

Firstly, thank you for your sharing your great work and code!

I would like to know your thoughts on SMT for ex-vivo imaging.
I was able to get fine SMT images in our _in-vivo_ human data; however, something appeared to go wrong with our SMT analysis on _ex-vivo_ mouse data.

Although I got a (apparently) normal micro-MD image (and a normal ICVF image from NODDI using MATLAB), almost all the value in the parenchyma, especially gray matter, was zero in SMT INVF and micro-FA images.
![ex-vivomouse_smt](https://cloud.githubusercontent.com/assets/11692488/18900487/92bfaf50-857c-11e6-9514-4815dadcb0ec.png)
(maxdiff = 1.88e-3; values are displayed in the range [0,1] except MD)

Any help would be hugely appreciated.

Daisuke

**Comment by ekaden** [comment]
To sort out this problem, I would need more information. You could either describe in detail what you have done so far, or you could send me a slice from the data set (extracted using, for example, [`fslroi`](http://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Fslutils)) including the b-values and gradient directions.

**Comment by dicemt** [comment]
I really appreciate your help.
I will send you the data set directly.

**Comment by ekaden** [comment]
The problem is that the b-values, here 1000 and 2000 s/mm², are chosen too low for an ex-vivo diffusion experiment. In this low b-value regime the decay of the mean diffusion signal is almost monoexponential, hence suggesting an isotropic microscopic diffusion process. Therefore, the microscopic FA as well as the intra-neurite volume fraction are close to zero. More typical b-values are, for example, 3000 and 6000 s/mm² as in [Kaden et al. (NeuroImage, 2016)](http://dx.doi.org/10.1016/j.neuroimage.2016.06.002).

Regarding the so-called intra-cellular volume fraction (ICVF) map from NODDI, this experiments demonstrates that NODDI suggests microscopic anisotropy even in the case when the signal does not include such information, thus is highly misleading, if not flawed ([Kaden et al., NeuroImage, 2016](http://dx.doi.org/10.1016/j.neuroimage.2016.06.002)).
