### ISSUE TITLE
Gradient directions not normalised message

### ISSUE THREAD

**Issue by NeuroImagingWorld** [ekaden/smt#3]
Hi,

   Thank you for the great work on SMT. We are trying to run the analysis fitmcmicro/fitmicrodt on our dataset, but getting following message when using FSL format bvecs.

_test.bvec has diffusion gradient directions which are not normalised._ 

Also tried to normalize the vectors to make sure they are unit length and tested, still getting this message. Can you please assist if you have a sample data for bvecs or grads file.

Thanks,
Prasanna

**Comment by ekaden** [comment]
The software checks if the gradient directions are normalised using a certain numerical criterion. Since normalisation may or may not require to modify the b-values too, SMT does not do that automatically.

You could normalise the gradient directions beforehand using the following MATLAB code (assuming that the b-values do not need to be adjusted):

```MATLAB
bvecs = load('bvecs');
bvecs_norm = bvecs./sqrt(sum(bvecs.^2, 1));
save('bvecs_norm', 'bvecs_norm', '-ascii'); 
```

Furthermore, I increased the numerical tolerance for the gradient direction normalisation check in the latest commit 9ad82761f94766ecbf646bceac6bf634e09da983.

**Comment by NeuroImagingWorld** [comment]
Thank you! Applying the correction seem to be working fine now. Only modification to above script is
bvecs_norm = bvecs./repmat(sqrt(sum(bvecs.^2, 1)),3,1);

Thanks,
Prasanna

**Comment by ekaden** [comment]
Right, the MATLAB code I provided requires [implicit expansion](http://blogs.mathworks.com/loren/2016/10/24/matlab-arithmetic-expands-in-r2016b/) introduced in R2016b.
