### ISSUE TITLE
Unable to read big image files

### ISSUE THREAD

**Issue by albertofpena** [ekaden/smt#4]
Hi, SMT team:

First of all, I want to thank you for sharing your great work with the community. 

I've found a problem when trying to use the software with compressed Human Connectome Project images. The issue seems to be that gzread returns an int with the number of bytes read. In the case of HCP images, the number of bytes read is ~4GB, which is greater than the max of a 32-bit signed int. With the uncompressed images, the software runs perfectly. Maybe a fix could be reading the volume in chunks.

Also, I had an error while compiling the current master branch. It seems CMakeLists.txt is missing some info to link the pthread library. I've fixed this in my machine adding the following lines to the CMakeLists.txt:

```
target_link_libraries (gaussianfit ${CMAKE_THREAD_LIBS_INIT})
target_link_libraries (ricianfit ${CMAKE_THREAD_LIBS_INIT})
target_link_libraries (fitmicrodt ${CMAKE_THREAD_LIBS_INIT})
target_link_libraries (fitmcmicro ${CMAKE_THREAD_LIBS_INIT})
```

I hope that helps.
Alberto

**Comment by ekaden** [comment]
Thanks for your interest in SMT!

Indeed, only compressed files of up to ~ 2 GB (uncompressed size) can be read and written due to the limitations of `gzread` and `gzwrite` you describe. Thank you for pointing out this issue. I shall try to fix the problem. As you say, a workaround is to run SMT on uncompressed datasets.

I added the thread library to use when linking in the latest commit f2936c187a0d9913f4bc275fb9c8efc6e1ecfa5d.

**Comment by albertofpena** [comment]
Thanks for your quick response and the fix, Enrico!

**Comment by ekaden** [comment]
It should be possible to read and write compressed files larger than 2 GB (uncompressed size) with commit 34b168ebfbcb655a89ab68863d9358a0e06cb46c. Again, thanks for pointing out this issue.

**Comment by albertofpena** [comment]
I'm running fitmicrodt and seems to work perfectly. Thanks for solving the issue!
